import { SalaryRule, RuleCategory } from '@prisma/client';

export interface RuleCalculationResult {
  code: string;
  name: string;
  category: RuleCategory;
  sequence: number;
  amount: number;
}

export interface PayrollContext {
  contract: {
    wage: number;
    position: string;
  };
  workedRatio: number; // e.g. 22 / 22 = 1.0, or 20 / 22 = 0.909
  workedDays: number;
  standardWorkingDays: number;
  [key: string]: any;
}

/**
 * Safely evaluates a simple mathematical expression given a scope context.
 */
function evaluateExpression(expr: string, context: Record<string, number>): number {
  let cleaned = expr.trim();

  // Replace recognized context variables with their numbers
  // Sort keys by length descending to avoid partial matches (e.g. GROSS before GRO)
  const keys = Object.keys(context).sort((a, b) => b.length - a.length);
  for (const key of keys) {
    const regex = new RegExp(`\\b${key}\\b`, 'g');
    cleaned = cleaned.replace(regex, context[key].toString());
  }

  // Handle contract.wage
  cleaned = cleaned.replace(/\bcontract\.wage\b/g, context['contract_wage']?.toString() || '0');

  // Security check: only allow numbers, spaces, and math operators + - * / ( ) .
  if (!/^[\d\s+\-*/().]+$/.test(cleaned)) {
    // If not a pure math expression, try parseFloat
    const parsed = parseFloat(cleaned);
    return isNaN(parsed) ? 0 : parsed;
  }

  try {
    // Safe numeric evaluation
    const fn = new Function(`return (${cleaned});`);
    const result = fn();
    return typeof result === 'number' && !isNaN(result) ? Math.round(result * 100) / 100 : 0;
  } catch {
    return 0;
  }
}

/**
 * Evaluates whether an optional rule condition passes.
 */
function evaluateCondition(condition: string | null | undefined, context: Record<string, number>): boolean {
  if (!condition || condition.trim().toLowerCase() === 'true' || condition.trim() === '') {
    return true;
  }

  let cleaned = condition.trim();
  cleaned = cleaned.replace(/\bcontract\.wage\b/g, context['contract_wage']?.toString() || '0');

  for (const key of Object.keys(context)) {
    const regex = new RegExp(`\\b${key}\\b`, 'g');
    cleaned = cleaned.replace(regex, context[key].toString());
  }

  // Allow basic comparisons: >=, <=, >, <, ==, !=
  if (/^[\d\s+\-*/().><=!]+$/.test(cleaned)) {
    try {
      const fn = new Function(`return Boolean(${cleaned});`);
      return Boolean(fn());
    } catch {
      return true;
    }
  }

  return true;
}

/**
 * Sequential Salary Rule Engine.
 * Iterates through rules in order of sequence, computing values and building the salary slip.
 */
export function executeSalaryRules(
  rules: SalaryRule[],
  context: PayrollContext
): {
  lines: RuleCalculationResult[];
  grossSalary: number;
  totalDeductions: number;
  netSalary: number;
} {
  // Sort strictly by sequence ascending
  const sortedRules = [...rules].sort((a, b) => a.sequence - b.sequence);

  const lines: RuleCalculationResult[] = [];
  const evalContext: Record<string, number> = {
    contract_wage: context.contract.wage,
    worked_ratio: context.workedRatio,
    worked_days: context.workedDays,
    standard_days: context.standardWorkingDays,
    GROSS: 0,
    DEDUCTIONS: 0,
  };

  let gross = 0;
  let deductions = 0;

  for (const rule of sortedRules) {
    // Check condition
    if (!evaluateCondition(rule.condition, evalContext)) {
      continue;
    }

    let amount = 0;

    switch (rule.calculationType) {
      case 'FIXED':
        amount = parseFloat(rule.value) || 0;
        break;

      case 'PERCENTAGE':
      case 'FORMULA':
        amount = evaluateExpression(rule.value, evalContext);
        break;
    }

    // Apply worked ratio proration to BASIC salary
    if (rule.category === RuleCategory.BASIC && context.workedRatio < 1.0) {
      amount = Math.round(amount * context.workedRatio * 100) / 100;
    }

    amount = Math.round(amount * 100) / 100;

    // Track running totals
    if (rule.category === RuleCategory.BASIC || rule.category === RuleCategory.ALLOWANCE) {
      gross += amount;
      evalContext['GROSS'] = gross;
    } else if (rule.category === RuleCategory.DEDUCTION) {
      deductions += amount;
      evalContext['DEDUCTIONS'] = deductions;
    }

    // Register this rule's output in the context for subsequent rules
    evalContext[rule.code] = amount;

    lines.push({
      code: rule.code,
      name: rule.name,
      category: rule.category,
      sequence: rule.sequence,
      amount,
    });
  }

  gross = Math.round(gross * 100) / 100;
  deductions = Math.round(deductions * 100) / 100;
  const netSalary = Math.round(Math.max(0, gross - deductions) * 100) / 100;

  // If a NET rule line was generated by formula, make sure its amount matches netSalary
  const netLine = lines.find((l) => l.category === RuleCategory.NET);
  if (netLine) {
    netLine.amount = netSalary;
  }

  return {
    lines,
    grossSalary: gross,
    totalDeductions: deductions,
    netSalary,
  };
}
